
[env]
TERM = "xterm-256color"

[font]
size = 9

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

# Arch install: pacman -S ttf-jetbrains-mono-nerd
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 0.9

[keyboard]
bindings = [
  { action = "IncreaseFontSize", key = "Plus", mods = "Control" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
  { action = "ResetFontSize", key = "Key0", mods = "Control" },
]

[general]
import = [
    "~/.config/alacritty/colorschemes/tokyo-night.toml"
]
